version: "3.9"

services:
  webapp:
    restart: always
    build: 
      context: ./
      dockerfile: Dockerfile
    container_name: webapp
    volumes:
      - /app/node_modules
      - ./:/app
    ports:
      - 80:80
    depends_on:
      - mongo
    environment:
      NODE_ENV: ${NODE_ENV}
      MONGO_URI: mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongo
    networks:
      - mongo-nodejs-webapp  
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes:
      - mongo-data:/data/db
    networks:
      - mongo-nodejs-webapp
networks:
  mongo-nodejs-webapp:
    driver: bridge
volumes:
 mongo-data:
  driver: local